version: '3.3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vscodeexample
    ports:
      - 127.0.0.1:9922:22
    volumes:
      - ./code/:/code/
    environment:
      DEV: 'True'
